# Generated by Django 3.1.6 on 2021-04-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_auto_20210416_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryitem',
            name='quantity_inhand',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
